### ISSUE TITLE
INFOGRAFÍA-EDUARDO-TOMAS-6US-IS

### ISSUE THREAD

**Issue by ToniDepp** [SistemasTecTlaxiaco/actividad-1-infografia-ToniDepp-1#1]
[INFOGRAFÍA-EDUARDO-TOMAS-6US.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-ToniDepp-1/files/14235599/INFOGRAFIA-EDUARDO-TOMAS-6US.pdf)

**Comment by 2003lulu** [comment]
En creatividad del diseño es bueno, pero podría mejorar.
18/20

**Comment by josealfredo79** [comment]
Falta la bibliografia de la cual se obtuvo informacion...
